config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index', as: :tasks

  get '/tasks/new', to: 'tasks#new', as: :new_task
  post '/tasks', to: 'tasks#create'

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_restaurant
  patch '/tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  get '/tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # list all tasks
  # Create a view with name index.html.erb
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    # function migrated to before_action (private method set_restaurant)
    #@task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    new_task = Task.create(task_params)
    redirect_to task_path(new_task)
  end

  def edit
    # function migrated to before_action (private method set_restaurant)
    #@task = Task.find(params[:id])
  end

  def update
    # function migrated to before_action (private method set_restaurant)
    #@task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # function migrated to before_action (private method set_restaurant)
    #@task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_restaurant
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <p>
    <%= f.label(:title)%>
    <%= f.text_field(:title)%>
  </p>
  <p>
    <%= f.label(:details)%>
    <%= f.text_area(:details)%>
  </p>
  <p>
    <%= f.label(:completed)%>
    <%= f.check_box(:completed)%>
  </p>

  <%= f.submit("UPDATE  ")%>
<%end%>

<%=link_to("Tasks List", tasks_path)%>

app/views/tasks/index.html.erb
<%# @task created in the controller - has all tasks%>
<div class="container">
  <div class="table">
    <h1>TASKS</h1>
    <%@tasks.each do |task|%>
    <div class="row">
      <div class="column">
        <input type="checkbox" <%="checked" if task.completed %>>
      </div>
      <div class="column" style="margin-right: 15px;">
        <%= link_to(task.title, task_path(task))%>
      </div>
      <%= link_to("delete", task_path(task), class: "buttom", method: :delete, data: { confirm: 'Are you sure?'} )%>
      <%# link_to 'Remove this Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you Sure?' }%>
    </div>
    <%end%>
  </div>
  <h3><%=link_to("Add a New Task", new_task_path)%></h3>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <p>
    <%= f.label(:title)%>
    <%= f.text_field(:title)%>
  </p>
  <p>
    <%= f.label(:details)%>
    <%= f.text_area(:details)%>
  </p>

  <%= f.submit("CREATE")%>
<%end%>

<%=link_to("Tasks List", tasks_path)%>

<!--     t.string "title"
    t.string "details"
    t.boolean "completed", default: false -->

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex justify-between">
    <h1><%=@task.title%></h1>
    <%= link_to("Edit", edit_restaurant_path, class: "buttom")%>
  </div>
  <p class="description"><%=@task.details%></p>
  <p> <input id="completed"type="checkbox" <%="checked" if @task.completed%>> This Task is completed</p>
  <%=link_to("Back to list", tasks_path) %>
</div>